name: QA Lab S3 Smoke Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  s3-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::968062515037:role/qa-lab-github-actions
          aws-region: us-east-2

      - name: Create test file
        run: |
          echo '{ "status": "ok", "source": "qa-lab-smoke-test" }' > test.json

      - name: Upload to S3
        run: |
          aws s3 cp test.json s3://qa-lab-results-dev/dev/qa-lab/smoke/test.json